const INTERESTS=['Faith','Food & Brunch','Fitness','Sports','Parents','Arts & Culture','Medical','Students','Volunteering','Gaming','Outdoors','Music','Nightlife','Wellness','Professional','Neighborhood','Travel','Books & Ideas','Formula One'];let token=localStorage.getItem('in-token')||'',me=null,items=[],view='feed',selected=new Set(),createType='plan',createTags=new Set(),profileTags=new Set(),signupTags=new Set();const feed=document.querySelector('#feed'),detailDialog=document.querySelector('#detailDialog'),detail=document.querySelector('#detail'),createDialog=document.querySelector('#createDialog'),profileDialog=document.querySelector('#profileDialog'),onboarding=document.querySelector('#onboardingDialog');
const api=async(path,opts={})=>{const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Something went wrong');return data};const toast=t=>{const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)};const esc=s=>(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function pills(el,set){el.innerHTML=INTERESTS.map(i=>`<button type="button" class="interest-pill ${set.has(i)?'active':''}" data-i="${i}">${i}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{set.has(b.dataset.i)?set.delete(b.dataset.i):set.add(b.dataset.i);pills(el,set);if(el.id==='interestFilters')render()})}
function greeting(){const h=new Date().getHours();return h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING'}
async function boot(){if(!token){setupOnboarding();onboarding.showModal();return}try{me=await api('/api/me');await refresh();afterLogin();handleInviteParams()}catch(e){localStorage.removeItem('in-token');token='';setupOnboarding();onboarding.showModal()}}
function setupOnboarding(){pills(document.querySelector('#signupInterests'),signupTags);document.querySelector('#onboardingForm').onsubmit=async e=>{e.preventDefault();try{const data=await api('/api/signup',{method:'POST',body:JSON.stringify({name:document.querySelector('#signupName').value,neighborhood:document.querySelector('#signupNeighborhood').value,interests:[...signupTags]})});token=data.token;me=data.user;localStorage.setItem('in-token',token);onboarding.close();await refresh();afterLogin();handleInviteParams()}catch(err){toast(err.message)}}}
function afterLogin(){document.querySelector('#greeting').textContent=`${greeting()}, ${me.name.toUpperCase()}.`;document.querySelector('#profileOpen').textContent=(me.name[0]||'?').toUpperCase();pills(document.querySelector('#interestFilters'),selected);pills(document.querySelector('#createTags'),createTags);profileTags=new Set(me.interests||[]);pills(document.querySelector('#profileInterests'),profileTags);render()}
async function refresh(){items=await api('/api/feed');render()}
function filtered(arr){if(!selected.size)return arr;return [...arr].sort((a,b)=>(b.tags||[]).filter(t=>selected.has(t)).length-(a.tags||[]).filter(t=>selected.has(t)).length)}
function who(list){if(!list?.length)return 'No one yet';const names=list.map(x=>x.name);return names.length<=3?names.join(', '):`${names.slice(0,2).join(', ')} + ${names.length-2} others`}
function card(p){const idea=p.type==='idea';const count=idea?p.interestedUsers.length:p.memberUsers.length;return `<article class="event-card ${idea?'idea-card':''}"><div class="event-meta"><span>${esc(p.when)}</span><span>${esc(p.place)}</span></div><div class="event-tags">${(p.tags||[]).map(t=>`<span class="interest-pill small">${esc(t)}</span>`).join('')}</div><div class="status-label ${idea?'idea-label':'live-plan'}">${p.status==='ended'?'ENDED':idea?'I\'D BE IN':'HAPPENING'}</div><h2 class="event-title">${esc(p.title)}</h2><p class="event-desc">${esc(p.description)}</p><div class="organizer-row"><div class="avatar">${esc((p.organizer?.name||'?')[0])}</div><div><strong>${esc(p.organizer?.name||'Someone')} ${idea?'wants to do this':'is doing this'}</strong><div class="connection">${idea?`${count} ${count===1?'person would':'people would'} be in`:`${who(p.memberUsers)} ${count===1?'is':'are'} IN`}</div></div></div>${p.status==='ended'?`<button class="ghost wide" onclick="openPlan('${p.id}')">IN ENDED · ROOM CLOSED</button>`:`<button class="primary wide" onclick="actOn('${p.id}')">${idea?(p.isInterested?'YOU’D BE IN':"I'D BE IN"):(p.isMember?'OPEN IN':"I'M IN")}</button>`}</article>`}
function render(){if(!me)return;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#interestZone').style.display=view==='feed'||view==='ideas'?'block':'none';document.querySelector('#masthead').style.display=view==='feed'||view==='ideas'?'block':'none';if(view==='feed')feed.innerHTML=filtered(items.filter(x=>x.type==='plan')).map(card).join('')||empty('Nothing is happening yet. Create the first IN.');if(view==='ideas')feed.innerHTML=filtered(items.filter(x=>x.type==='idea')).map(card).join('')||empty('No ideas yet. Put one out there.');if(view==='network')renderNetwork()}
function empty(t){return `<section class="event-card"><div class="eyebrow">YOUR IN</div><h2 class="event-title">${t}</h2><button class="primary" onclick="createDialog.showModal()">CREATE SOMETHING</button></section>`}
window.actOn=async pid=>{const p=items.find(x=>x.id===pid);try{if((p.type==='idea'&&!p.isInterested)||(p.type==='plan'&&!p.isMember)){await api(`/api/plans/${pid}/join`,{method:'POST',body:'{}'});await refresh()}openPlan(pid)}catch(e){toast(e.message)}};
window.openPlan=async pid=>{try{const p=await api(`/api/plans/${pid}`);const people=p.type==='idea'?p.interestedUsers:p.memberUsers;detail.innerHTML=`<div class="detail-head"><div><div class="eyebrow">${p.type==='idea'?'SHARED INTENT':'YOU’RE IN'}</div><h2 class="detail-title">${esc(p.title)}</h2></div><button class="icon-btn" onclick="detailDialog.close()">×</button></div><p class="page-copy">${esc(p.when)} · ${esc(p.place)}</p><p>${esc(p.description)}</p><div class="participant-list">${people.map(u=>`<span class="person-chip">${esc(u.name)}</span>`).join('')}</div>${p.type==='idea'?ideaDetail(p):planDetail(p)}`;detailDialog.showModal();if(p.type==='plan'&&p.isMember&&p.status==='active')loadMessages(p.id)}catch(e){toast(e.message)}};
function ideaDetail(p){return `${p.isOrganizer?`<div class="rule-box"><strong>Enough people?</strong><br>Turn this into a real IN when the details are ready.</div><div class="field-row"><input id="realWhen" value="${esc(p.when)}"><input id="realPlace" value="${esc(p.place)}"></div><button class="primary wide" onclick="makeReal('${p.id}')">MAKE IT AN IN →</button>`:`<div class="rule-box"><strong>You’d be in.</strong><br>${esc(p.organizer?.name)} can turn this into a real plan when the group is ready.</div>`}`}
function planDetail(p){if(p.status==='ended')return `<div class="ended-box"><h3>Room closed.</h3><p>This IN ended. There are still no person-to-person DMs.</p></div>`;if(!p.isMember)return `<button class="primary wide" onclick="actOn('${p.id}')">I'M IN</button>`;return `<div class="pin-box"><div class="section-kicker">MEETING PIN</div><h3 id="pinText">${esc(p.pin||'Not dropped yet')}</h3>${p.isOrganizer?`<div class="chat-compose"><input id="pinInput" placeholder="Corner booth at Billy’s"><button class="ghost" onclick="setPin('${p.id}')">UPDATE</button></div>`:''}</div><div class="chat-box"><div class="section-kicker">TEMPORARY IN ROOM</div><div id="chatLog" class="chat-log"></div><div class="chat-compose"><input id="messageInput" placeholder="Message everyone in this IN…"><button class="primary" onclick="sendMessage('${p.id}')">SEND</button></div><div class="safety-line">Group room only · No dating/sexual solicitation · No DMs</div></div>${p.isOrganizer?`<button class="ghost wide" onclick="endIn('${p.id}')">END THIS IN</button>`:''}`}
async function loadMessages(pid){try{const x=await api(`/api/plans/${pid}/messages`);document.querySelector('#chatLog').innerHTML=x.messages.map(m=>`<div class="msg"><strong>${esc(m.user?.name||'IN')}</strong><span>${esc(m.text)}</span></div>`).join('')||'<div class="muted">No messages yet.</div>'}catch(e){toast(e.message)}}
window.sendMessage=async pid=>{const input=document.querySelector('#messageInput');const text=input.value.trim();if(!text)return;try{await api(`/api/plans/${pid}/messages`,{method:'POST',body:JSON.stringify({text})});input.value='';loadMessages(pid)}catch(e){toast(e.message)}};
window.setPin=async pid=>{const pin=document.querySelector('#pinInput').value.trim();try{const x=await api(`/api/plans/${pid}/pin`,{method:'POST',body:JSON.stringify({pin})});document.querySelector('#pinText').textContent=x.pin||'Not dropped yet';toast('Meeting pin updated')}catch(e){toast(e.message)}};
window.endIn=async pid=>{try{await api(`/api/plans/${pid}/end`,{method:'POST',body:'{}'});detailDialog.close();await refresh();toast('IN ended. Group room closed.')}catch(e){toast(e.message)}};
window.makeReal=async pid=>{try{await api(`/api/plans/${pid}/make-real`,{method:'POST',body:JSON.stringify({when:document.querySelector('#realWhen').value,place:document.querySelector('#realPlace').value})});detailDialog.close();view='feed';await refresh();toast('It’s a real IN now.')}catch(e){toast(e.message)}};
async function renderNetwork(){try{const network=await api('/api/network');feed.innerHTML=`<section class="page"><div class="eyebrow">MY IN</div><h2 class="page-title">Your world, connected.</h2><p class="page-copy">No followers. No inbox. These are people who can make the city feel less random.</p><div class="connection-list">${network.length?network.map(u=>`<div class="connection-card"><div class="avatar">${esc(u.name[0])}</div><div><strong>${esc(u.name)}</strong><span>DIRECTLY IN</span><small>${esc(u.neighborhood||'New York')}</small></div></div>`).join(''):'<div class="event-card">Your network starts with one invite.</div>'}</div><button class="primary wide" onclick="invitePerson()">INVITE SOMEONE INTO YOUR IN</button><div class="rule-box"><strong>No person-to-person DMs.</strong><br>Being connected means you can see each other’s eligible plans. Conversation happens inside an active IN.</div></section>`}catch(e){toast(e.message)}}
window.invitePerson=async()=>{try{const x=await api('/api/network/invite',{method:'POST',body:'{}'});await navigator.clipboard.writeText(x.link).catch(()=>{});detail.innerHTML=`<div class="detail-head"><div><div class="eyebrow">BRING SOMEONE IN</div><h2 class="detail-title">Invite link ready.</h2></div><button class="icon-btn" onclick="detailDialog.close()">×</button></div><p class="page-copy">Send this to someone you actually know. When they join, they become directly IN with you.</p><div class="rule-box link-box">${esc(x.link)}</div><button class="primary wide" onclick="navigator.clipboard.writeText('${x.link}');toast('Copied')">COPY LINK</button>`;detailDialog.showModal()}catch(e){toast(e.message)}};
async function handleInviteParams(){const u=new URL(location.href);const code=u.searchParams.get('network');if(code&&me){try{await api('/api/network/accept',{method:'POST',body:JSON.stringify({code})});toast('You’re connected on IN');history.replaceState({},'',location.pathname);if(view==='network')renderNetwork()}catch(e){toast(e.message)}}}
function openProfile(){document.querySelector('#profileName').value=me.name;document.querySelector('#profileNeighborhood').value=me.neighborhood||'';profileTags=new Set(me.interests||[]);pills(document.querySelector('#profileInterests'),profileTags);profileDialog.showModal()}
document.querySelector('#profileForm').onsubmit=async e=>{e.preventDefault();try{me=await api('/api/me',{method:'PUT',body:JSON.stringify({name:document.querySelector('#profileName').value,neighborhood:document.querySelector('#profileNeighborhood').value,interests:[...profileTags]})});profileDialog.close();afterLogin();toast('Profile saved')}catch(err){toast(err.message)}};
document.querySelector('#signOut').onclick=()=>{localStorage.removeItem('in-token');location.reload()};document.querySelector('#profileOpen').onclick=openProfile;document.querySelector('#mobileProfile').onclick=openProfile;document.querySelector('#profileClose').onclick=()=>profileDialog.close();document.querySelector('#inviteNetwork').onclick=invitePerson;document.querySelector('#createOpen').onclick=()=>createDialog.showModal();document.querySelector('#mobileCreate').onclick=()=>createDialog.showModal();document.querySelector('#createClose').onclick=()=>createDialog.close();document.querySelectorAll('.type-choice').forEach(b=>b.onclick=()=>{createType=b.dataset.type;document.querySelectorAll('.type-choice').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#createSubmit').textContent=createType==='idea'?'PUT THE IDEA OUT THERE':'POST THE IN'});document.querySelector('#createForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/plans',{method:'POST',body:JSON.stringify({type:createType,title:document.querySelector('#createTitle').value,description:document.querySelector('#createDescription').value,when:document.querySelector('#createWhen').value,place:document.querySelector('#createPlace').value,tags:[...createTags]})});createDialog.close();e.target.reset();createTags.clear();pills(document.querySelector('#createTags'),createTags);view=createType==='idea'?'ideas':'feed';await refresh();toast(createType==='idea'?"People can now say they'd be in":"Your IN is live") }catch(err){toast(err.message)}};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector('#clearFilter').onclick=()=>{selected.clear();pills(document.querySelector('#interestFilters'),selected);render()};boot();