const express=require('express');const path=require('path');const crypto=require('crypto');const app=express();app.use(express.json());app.use(express.static(__dirname));
const bad=[/\b(hook ?up|hooking up|sex|sexual|make out|dtf|nudes?|one night stand|friends with benefits|speed dating)\b/i,/\b(looking for|meet)\s+(women|men|girls|guys)\b/i,/\b(single women|single men|single girls|single guys)\b/i];const safe=t=>!bad.some(r=>r.test(t||''));const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
let db={users:{},tokens:{},edges:[],plans:{},notifications:[],reports:[],networkInvites:{}};
function seed(){const add=(uid,name,neighborhood,interests)=>db.users[uid]={id:uid,name,neighborhood,interests,createdAt:now()};add('afton','Afton','Upper East Side',['Faith','Food & Brunch','Wellness']);add('marney','Marney','Upper East Side',['Medical','Travel','Food & Brunch']);add('alex','Alex','Upper West Side',['Sports','Fitness','Formula One']);add('hannah','Hannah','Upper West Side',['Sports','Outdoors','Arts & Culture']);db.edges=[['marney','afton'],['marney','hannah']];const p1={id:'church',type:'plan',title:'Church → Boozy Brunch',description:'Church Sunday morning, then brunch after. Come for either or both.',when:'Sunday · 10:30 AM',place:'Upper East Side',organizerId:'afton',tags:['Faith','Food & Brunch'],status:'active',members:['afton'],interested:[],messages:[{id:id(),userId:'afton',text:'Church first — brunch right after. Join either part.',at:now()}],pin:null,createdAt:now()};const p2={id:'f1',type:'idea',title:'Watch Formula One together 🏎️',description:'Bar, apartment, whatever. Just thought it would be fun to watch with people who are actually into it.',when:'Sunday morning',place:'Manhattan · flexible',organizerId:'alex',tags:['Formula One','Sports'],status:'active',members:[],interested:['alex'],messages:[],pin:null,createdAt:now()};const p3={id:'tennis',type:'idea',title:'Saturday tennis 🎾',description:'Intermediate-ish doubles. Easy, recurring, no league commitment.',when:'Saturdays',place:'UWS / Riverside',organizerId:'hannah',tags:['Sports','Outdoors'],status:'active',members:[],interested:['hannah'],messages:[],pin:null,createdAt:now()};db.plans[p1.id]=p1;db.plans[p2.id]=p2;db.plans[p3.id]=p3;}seed();
function auth(req,res,next){const token=(req.headers.authorization||'').replace('Bearer ','');const uid=db.tokens[token];if(!uid)return res.status(401).json({error:'Sign in required'});req.user=db.users[uid];next();}
function publicUser(u){return u&&({id:u.id,name:u.name,neighborhood:u.neighborhood,interests:u.interests});}
function hydratePlan(p,viewer){const org=db.users[p.organizerId];const memberUsers=p.members.map(x=>publicUser(db.users[x])).filter(Boolean);const interestedUsers=p.interested.map(x=>publicUser(db.users[x])).filter(Boolean);return {...p,organizer:publicUser(org),memberUsers,interestedUsers,isOrganizer:viewer?.id===p.organizerId,isMember:p.members.includes(viewer?.id),isInterested:p.interested.includes(viewer?.id)};}
app.post('/api/signup',(req,res)=>{const name=(req.body.name||'').trim();if(!name)return res.status(422).json({error:'Name required'});const uid=id();const token=id();db.users[uid]={id:uid,name,neighborhood:(req.body.neighborhood||'New York').trim(),interests:Array.isArray(req.body.interests)?req.body.interests.slice(0,12):[],createdAt:now()};db.tokens[token]=uid;res.json({token,user:publicUser(db.users[uid])});});
app.post('/api/login-demo',(req,res)=>{const uid=req.body.userId||'alex';if(!db.users[uid])return res.status(404).json({error:'User not found'});const token=id();db.tokens[token]=uid;res.json({token,user:publicUser(db.users[uid])});});
app.get('/api/me',auth,(req,res)=>res.json(publicUser(req.user)));
app.put('/api/me',auth,(req,res)=>{if(req.body.name)req.user.name=req.body.name.trim();if(req.body.neighborhood)req.user.neighborhood=req.body.neighborhood.trim();if(Array.isArray(req.body.interests))req.user.interests=req.body.interests.slice(0,12);res.json(publicUser(req.user));});
app.get('/api/feed',auth,(req,res)=>{const items=Object.values(db.plans).filter(p=>p.status!=='deleted').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(p=>hydratePlan(p,req.user));res.json(items);});
app.post('/api/plans',auth,(req,res)=>{const title=(req.body.title||'').trim(),description=(req.body.description||'').trim();if(!title)return res.status(422).json({error:'Give it a name'});if(!safe(title+' '+description))return res.status(422).json({error:'IN is for activities and real-world plans, not dating or sexual solicitation.'});const type=req.body.type==='idea'?'idea':'plan';const pid=id();const p={id:pid,type,title,description,when:(req.body.when||'Flexible').trim(),place:(req.body.place||'New York').trim(),organizerId:req.user.id,tags:Array.isArray(req.body.tags)?req.body.tags.slice(0,8):[],status:'active',members:type==='plan'?[req.user.id]:[],interested:type==='idea'?[req.user.id]:[],messages:[],pin:null,createdAt:now()};db.plans[pid]=p;res.json(hydratePlan(p,req.user));});
app.get('/api/plans/:id',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p)return res.status(404).json({error:'IN not found'});res.json(hydratePlan(p,req.user));});
app.post('/api/plans/:id/join',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p||p.status!=='active')return res.status(404).json({error:'This IN is not active'});if(p.type==='idea'){if(!p.interested.includes(req.user.id))p.interested.push(req.user.id);}else{if(!p.members.includes(req.user.id))p.members.push(req.user.id);}res.json(hydratePlan(p,req.user));});
app.post('/api/plans/:id/make-real',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p||p.type!=='idea')return res.status(404).json({error:'Idea not found'});if(p.organizerId!==req.user.id)return res.status(403).json({error:'Only the organizer can make this an IN'});p.type='plan';p.members=[...new Set([p.organizerId,...p.interested])];p.interested=[];p.when=(req.body.when||p.when).trim();p.place=(req.body.place||p.place).trim();p.messages.push({id:id(),userId:req.user.id,text:'This is happening. Details are set.',at:now(),system:true});res.json(hydratePlan(p,req.user));});
app.get('/api/plans/:id/messages',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p)return res.status(404).json({error:'IN not found'});if(p.type!=='plan'||!p.members.includes(req.user.id))return res.status(403).json({error:'Join the IN to access its temporary group room'});res.json({active:p.status==='active',messages:p.messages.map(m=>({...m,user:publicUser(db.users[m.userId])}))});});
app.post('/api/plans/:id/messages',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p||p.type!=='plan')return res.status(404).json({error:'IN not found'});if(p.status!=='active')return res.status(410).json({error:'This IN ended. The room is closed.'});if(!p.members.includes(req.user.id))return res.status(403).json({error:'Join the IN first'});const text=(req.body.text||'').trim();if(!text)return res.status(422).json({error:'Message required'});if(!safe(text))return res.status(422).json({error:'Come for the thing. Dating or sexual solicitation is not allowed on IN.'});const m={id:id(),userId:req.user.id,text,at:now()};p.messages.push(m);res.json({...m,user:publicUser(req.user)});});
app.post('/api/plans/:id/pin',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p||p.organizerId!==req.user.id)return res.status(403).json({error:'Only the organizer can update the meeting pin'});p.pin=(req.body.pin||'').trim()||null;res.json({pin:p.pin});});
app.post('/api/plans/:id/end',auth,(req,res)=>{const p=db.plans[req.params.id];if(!p||p.organizerId!==req.user.id)return res.status(403).json({error:'Only the organizer can end this IN'});p.status='ended';res.json({ok:true});});
app.get('/api/network',auth,(req,res)=>{const direct=new Set();for(const [a,b] of db.edges){if(a===req.user.id)direct.add(b);if(b===req.user.id)direct.add(a);}res.json([...direct].map(x=>publicUser(db.users[x])).filter(Boolean));});
app.post('/api/network/invite',auth,(req,res)=>{const code=id().slice(0,8);db.networkInvites[code]={from:req.user.id,createdAt:now()};res.json({code,link:`${req.protocol}://${req.get('host')}/?network=${code}`});});
app.post('/api/network/accept',auth,(req,res)=>{const inv=db.networkInvites[req.body.code];if(!inv)return res.status(404).json({error:'Invite expired or invalid'});const edge=[inv.from,req.user.id];if(inv.from!==req.user.id&&!db.edges.some(([a,b])=>(a===edge[0]&&b===edge[1])||(a===edge[1]&&b===edge[0])))db.edges.push(edge);delete db.networkInvites[req.body.code];res.json({ok:true});});
app.post('/api/report',auth,(req,res)=>{db.reports.push({id:id(),userId:req.user.id,...req.body,at:now()});res.json({ok:true});});
app.get('/health',(req,res)=>res.json({ok:true,product:'IN',version:'0.5.0',mode:'usable-beta',features:['real-profiles','create-plan','create-idea','join','shared-group-room','meeting-pin','end-room','network-invites','no-dms','moderation']}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(process.env.PORT||3000);